"""add_missing_foreign_key_constraints

Revision ID: 629a6ca77da7
Revises: simplified_location_migration
Create Date: 2025-07-18 15:16:44.149879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '629a6ca77da7'
down_revision: Union[str, Sequence[str], None] = 'simplified_location_migration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Skipping unique constraint changes due to existing data conflicts
    # op.drop_constraint(op.f('uq_locations_name_level'), 'locations', type_='unique')
    # op.create_unique_constraint(None, 'locations', ['name'])
    
    op.alter_column('payment_plans', 'installments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('projects', 'amenities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###
    
    # ### manually added foreign key constraints ###
    # Add foreign key constraint for media table
    op.create_foreign_key('media_property_id_fkey', 'media', 'properties', ['property_id'], ['id'])
    
    # Add foreign key constraint for payment_plans table
    op.create_foreign_key('payment_plans_property_id_fkey', 'payment_plans', 'properties', ['property_id'], ['id'])
    
    # Add foreign key constraint for documents table
    op.create_foreign_key('documents_property_id_fkey', 'documents', 'properties', ['property_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### manually added foreign key constraints ###
    # Remove foreign key constraints
    op.drop_constraint('documents_property_id_fkey', 'documents', type_='foreignkey')
    op.drop_constraint('payment_plans_property_id_fkey', 'payment_plans', type_='foreignkey')
    op.drop_constraint('media_property_id_fkey', 'media', type_='foreignkey')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'amenities',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('payment_plans', 'installments',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # Note: Skipping unique constraint changes due to existing data conflicts
    # op.drop_constraint('uq_locations_name', 'locations', type_='unique')
    # op.create_unique_constraint(op.f('uq_locations_name_level'), 'locations', ['name', 'level'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
