"""hybrid normalized schema for properties and related tables

Revision ID: fd80e6630fc4
Revises: edddeb1db334
Create Date: 2025-07-18 10:39:52.678748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd80e6630fc4'
down_revision: Union[str, Sequence[str], None] = 'edddeb1db334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_ar', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_ar', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('developer', sa.String(), nullable=True),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_l1', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('slug_l1', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.String(), nullable=True),
    sa.Column('down_payment', sa.Float(), nullable=True),
    sa.Column('installments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('properties', sa.Column('agency_id', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'properties', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'properties', 'agents', ['agent_id'], ['id'])
    op.create_foreign_key(None, 'properties', 'agencies', ['agency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_column('properties', 'project_id')
    op.drop_column('properties', 'agent_id')
    op.drop_column('properties', 'agency_id')
    op.drop_table('payment_plans')
    op.drop_table('media')
    op.drop_table('locations')
    op.drop_table('documents')
    op.drop_table('projects')
    op.drop_table('agents')
    op.drop_table('agencies')
    # ### end Alembic commands ###
